replicaCount: 2

image:
  repository: tetianabahlai/api
  tag: latest

service:
  type: LoadBalancer
  port: 80

containerPort: 3001

env:
  - name: DB_HOST
    value: mysql
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: root
  - name: DB_PASS
    value: password

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi