apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    cloud.google.com/load-balancer-ipv4: "104.154.199.155"
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3001