replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/gke-project-462023/api/api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

containerPort: 3001

env:
  - name: DB_HOST
    value: mysql
  - name: DB_PORT
    value: "3306"
  - name: DB
    value: mydb
  - name: PORT
    value: "3001"

secretEnv:
  - name: DB_USER
    value: root
  - name: DB_PASS
    value: password
  - name: SESSION_SECRET
    value: supersecret

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi