replicaCount: 2
image:
  repository: us-central1-docker.pkg.dev/gke-project-462023/web/web
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
containerPort: 3000
env:
  - name: API_HOST
    value: "http://api:3001"
  - name: SESSION_SECRET
    value: "supersecret"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi